#vector database index details
vector-databases = ["--select index--","index"]#,"velux-index-1","novartis-index","penfed-index"]
velux-index-1_api_key = "89c890aa-ead7-4c56-93d4-57968c3698c2"
velux-index-1_environment = "asia-southeast1-gcp-free"
novartis-index_api_key = "312f1c16-1f6f-48ea-983a-f0a7b76a29ea"
novartis-index_environment = "gcp-starter"
penfed-index_api_key = "2d1b9675-5d6a-4a31-9a1f-7e1d7095b593"
penfed-index_environment = "us-west4-gcp-free"

#chatbot index details
index_name = "index"
index_api_key = "89c890aa-ead7-4c56-93d4-57968c3698c2"
index_environment = "asia-southeast1-gcp-free"


OPENAI_API_KEY = "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"